name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3

      - name: Install linters and setup stylelint
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard
          echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json

      - name: Run HTMLHint
        run: htmlhint index.html

      - name: Run stylelint
        run: stylelint style.css